//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CarInfoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CarInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double CarPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarDescriptionField;
        
        private double CarMaxSpeedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double CarPrice {
            get {
                return this.CarPriceField;
            }
            set {
                if ((this.CarPriceField.Equals(value) != true)) {
                    this.CarPriceField = value;
                    this.RaisePropertyChanged("CarPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CarDescription {
            get {
                return this.CarDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CarDescriptionField, value) != true)) {
                    this.CarDescriptionField = value;
                    this.RaisePropertyChanged("CarDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double CarMaxSpeed {
            get {
                return this.CarMaxSpeedField;
            }
            set {
                if ((this.CarMaxSpeedField.Equals(value) != true)) {
                    this.CarMaxSpeedField = value;
                    this.RaisePropertyChanged("CarMaxSpeed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarInfoServiceReference.CarInfoServiceSoap")]
    public interface CarInfoServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем carInfo из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Translate", ReplyAction="*")]
        Client.CarInfoServiceReference.TranslateResponse Translate(Client.CarInfoServiceReference.TranslateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Translate", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.CarInfoServiceReference.TranslateResponse> TranslateAsync(Client.CarInfoServiceReference.TranslateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TranslateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Translate", Namespace="http://tempuri.org/", Order=0)]
        public Client.CarInfoServiceReference.TranslateRequestBody Body;
        
        public TranslateRequest() {
        }
        
        public TranslateRequest(Client.CarInfoServiceReference.TranslateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TranslateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.CarInfoServiceReference.CarInfo carInfo;
        
        public TranslateRequestBody() {
        }
        
        public TranslateRequestBody(Client.CarInfoServiceReference.CarInfo carInfo) {
            this.carInfo = carInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TranslateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TranslateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.CarInfoServiceReference.TranslateResponseBody Body;
        
        public TranslateResponse() {
        }
        
        public TranslateResponse(Client.CarInfoServiceReference.TranslateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TranslateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.CarInfoServiceReference.CarInfo TranslateResult;
        
        public TranslateResponseBody() {
        }
        
        public TranslateResponseBody(Client.CarInfoServiceReference.CarInfo TranslateResult) {
            this.TranslateResult = TranslateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarInfoServiceSoapChannel : Client.CarInfoServiceReference.CarInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarInfoServiceSoapClient : System.ServiceModel.ClientBase<Client.CarInfoServiceReference.CarInfoServiceSoap>, Client.CarInfoServiceReference.CarInfoServiceSoap {
        
        public CarInfoServiceSoapClient() {
        }
        
        public CarInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.CarInfoServiceReference.TranslateResponse Client.CarInfoServiceReference.CarInfoServiceSoap.Translate(Client.CarInfoServiceReference.TranslateRequest request) {
            return base.Channel.Translate(request);
        }
        
        public Client.CarInfoServiceReference.CarInfo Translate(Client.CarInfoServiceReference.CarInfo carInfo) {
            Client.CarInfoServiceReference.TranslateRequest inValue = new Client.CarInfoServiceReference.TranslateRequest();
            inValue.Body = new Client.CarInfoServiceReference.TranslateRequestBody();
            inValue.Body.carInfo = carInfo;
            Client.CarInfoServiceReference.TranslateResponse retVal = ((Client.CarInfoServiceReference.CarInfoServiceSoap)(this)).Translate(inValue);
            return retVal.Body.TranslateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.CarInfoServiceReference.TranslateResponse> Client.CarInfoServiceReference.CarInfoServiceSoap.TranslateAsync(Client.CarInfoServiceReference.TranslateRequest request) {
            return base.Channel.TranslateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.CarInfoServiceReference.TranslateResponse> TranslateAsync(Client.CarInfoServiceReference.CarInfo carInfo) {
            Client.CarInfoServiceReference.TranslateRequest inValue = new Client.CarInfoServiceReference.TranslateRequest();
            inValue.Body = new Client.CarInfoServiceReference.TranslateRequestBody();
            inValue.Body.carInfo = carInfo;
            return ((Client.CarInfoServiceReference.CarInfoServiceSoap)(this)).TranslateAsync(inValue);
        }
    }
}
